name: Basic MLOps CI Workflow

on:
  push:
    branches:
      - main
      - vatsalya-changes
    paths:
      - 'data/**'
      - 'train/**'
      - 'requirements.txt'
  pull_request:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: python train/train.py

      - name: Upload Trained Model as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ./model/
      # ... (previous steps like Run Training Script)

      - name: Git Auto Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "coolvats"
          git config --global user.email "vatsalyamishra93@gmail.com"
          git add ./model/
          git commit -m "Update trained model [skip ci]" || echo "No changes to commit"
          git push
